FROM nginx:latest
WORKDIR /etc/nginx/conf.d
COPY ./default.conf ./default.conf
RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
RUN chown -R appuser:appgroup /var/cache/nginx /var/log/nginx /etc/nginx /var/run/
USER appuser
EXPOSE 80
